name: build
on:
  push:
  pull_request:

jobs:
  build:
    name: Node.js ${{ matrix.os }} ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [6, 8, 10, 12]
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - run: npm install
      - run: npm test
      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.node == 12
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

