name: Test
on:
  push:
  pull_request:

jobs:
  build:
    name: Node.js ${{ matrix.os }} ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [6, 8, 10, 12]
    steps:
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - run: npm i -g npm@latest
      - run: npm ci
      - run: npm test

